In [12]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

df = pd.read_csv('iraq1.csv')

/var/folders/1w/6vqfb5jj0nv8pf9fqf_nwwfh0000gn/T/ipykernel_34157/1513353998.py:6: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('iraq1.csv')

In [25]:
df

,Region,Datetime,Type,Category,Affiliation,Detained,Enemy_KIA,Friend_KIA,Civilian_KIA,Host_nation_KIA,Enemy_WIA,Friend_WIA,Civilian_WIA,Host_nation_WIA
0,MNF-W,2004-01-01 06:06,Explosive Hazard,IED Explosion,ENEMY,0,0,0,0,0,0,0,0,0
1,MNF-W,2004-01-01 14:02,Friendly Action,Confiscation,FRIEND,2,0,0,0,0,0,0,0,0
2,MND-N,2004-01-01 07:07,Enemy Action,Indirect Fire,ENEMY,0,0,0,0,0,0,0,0,0
3,MND-N,2004-01-01 12:12,Criminal Event,Murder,ENEMY,0,0,0,1,0,0,0,0,0
4,MNF-W,2004-01-01 12:12,Explosive Hazard,IED Found/Cleared,ENEMY,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390733,MND-N,2009-12-31 21:09,Explosive Hazard,IED Explosion,ENEMY,0,0,0,0,0,0,0,0,0
390734,MND-BAGHDAD,2009-12-31 22:10,Explosive Hazard,IED Found/Cleared,ENEMY,0,0,0,0,0,0,0,0,0
390735,MND-SE,2009-12-31 22:10,Non-Combat Event,Accident,NEUTRAL,0,0,0,3,0,0,0,0,0
390736,MND-BAGHDAD,2009-12-31 22:10,Explosive Hazard,Unexploded Ordnance,ENEMY,0,0,0,0,0,0,0,0,0
390737,MND-SE,2009-12-31 18:06,Enemy Action,Indirect Fire,ENEMY,0,0,0,0,0,0,1,0,0

In [34]:
df["Category"].

array(['IED EXPLOSION', 'CONFISCATION', 'INDIRECT FIRE', 'MURDER',
       'IED FOUND/CLEARED', 'RAID', 'CACHE FOUND/CLEARED', 'ACCIDENT',
       'DIRECT FIRE', 'OTHER', 'CORDON/SEARCH', 'DETAIN', 'TRIBAL FEUD',
       'ATTACK', 'SURVEILLANCE', 'EQUIPMENT FAILURE', 'ARSON',
       'UNKNOWN EXPLOSION', 'ARREST', 'UNEXPLODED ORDNANCE',
       'OTHER OFFENSIVE', 'BLUE-WHITE', 'THEFT', 'DEMONSTRATION',
       'IED SUSPECTED', 'MINE FOUND/CLEARED', 'KIDNAPPING',
       'SUPPORTING CF', 'MINE STRIKE', 'VEHICLE INTERDICTION', 'LOOTING',
       'ESCALATION OF FORCE', 'INDIRECT FIRE THREAT', 'SAFIRE',
       'IED HOAX', 'SMUGGLING', 'TCP', 'PATROL', 'ATTACK THREAT',
       'EXPLOSIVE REMNANTS OF WAR (ERW)/TURN IN', 'IED FALSE', 'SABOTAGE',
       'MEETING', 'MEDEVAC', 'DIRECT FIRE THREAT', 'BLUE-BLUE',
       'IED THREAT', 'CARJACKING', 'RECON', 'MURDER THREAT',
       'GREEN-GREEN', 'POLICE ACTIONS', 'ASSASSINATION', 'PROPAGANDA',
       'TESTS OF SECURITY', 'COUNTER MORTAR FIRE', 'INTIMIDATION',
       'REPETITIVE ACTIVITIES', 'BLUE-GREEN', 'SMALL UNIT ACTIONS',
       'SNIPER OPS', 'BORDER OPS', 'AMBUSH', 'SAFIRE THREAT',
       'CLOSE AIR SUPPORT', 'OTHER DEFENSIVE', 'GREEN-WHITE',
       'AMBUSH THREAT', 'GREEN-BLUE', 'MOVEMENT TO CONTACT', 'BREACHING',
       'COUNTER MORTAR PATROL', 'SUPPORTING AIF', 'ROCK THROWING',
       'SERMON', 'HIJACKING', 'THEFT THREAT', 'ARTY', 'DETENTION', 'UAV',
       'ASSASSINATION THREAT', 'KIDNAPPING THREAT', 'INTIMIDATION THREAT',
       'SMUGGLING THREAT', 'SNIPER OPS THREAT', 'CARJACKING THREAT',
       'SABOTAGE THREAT', 'CONVOY', 'NATURAL DISASTER', 'WHITE-BLUE',
       'EXTORTION', 'MUGGING', 'SMALL ARMS THREAT', 'LOOTING THREAT',
       'ELICITATION', 'DELIBERATE ATTACK', 'SEARCH AND ATTACK',
       'RAID THREAT', 'STAFF ESTIMATE', 'NAN', 'WHITE-WHITE',
       'WHITE-GREEN', 'EXPLOSIVE REMNANTS OF WAR (ERW) FOUND/CLEARED',
       'IED PRE-DETONATION', 'RECON THREAT', 'LASING', 'SHOOTING',
       'NONE SELECTED'], dtype=object)

In [30]:
df.fillna(0, inplace=True)

In [27]:
df

,Region,Datetime,Type,Category,Affiliation,Detained,Enemy_KIA,Friend_KIA,Civilian_KIA,Host_nation_KIA,Enemy_WIA,Friend_WIA,Civilian_WIA,Host_nation_WIA
0,MNF-W,2004-01-01 06:06,EXPLOSIVE HAZARD,IED EXPLOSION,ENEMY,0,0,0,0,0,0,0,0,0
1,MNF-W,2004-01-01 14:02,FRIENDLY ACTION,CONFISCATION,FRIEND,2,0,0,0,0,0,0,0,0
2,MND-N,2004-01-01 07:07,ENEMY ACTION,INDIRECT FIRE,ENEMY,0,0,0,0,0,0,0,0,0
3,MND-N,2004-01-01 12:12,CRIMINAL EVENT,MURDER,ENEMY,0,0,0,1,0,0,0,0,0
4,MNF-W,2004-01-01 12:12,EXPLOSIVE HAZARD,IED FOUND/CLEARED,ENEMY,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390733,MND-N,2009-12-31 21:09,EXPLOSIVE HAZARD,IED EXPLOSION,ENEMY,0,0,0,0,0,0,0,0,0
390734,MND-BAGHDAD,2009-12-31 22:10,EXPLOSIVE HAZARD,IED FOUND/CLEARED,ENEMY,0,0,0,0,0,0,0,0,0
390735,MND-SE,2009-12-31 22:10,NON-COMBAT EVENT,ACCIDENT,NEUTRAL,0,0,0,3,0,0,0,0,0
390736,MND-BAGHDAD,2009-12-31 22:10,EXPLOSIVE HAZARD,UNEXPLODED ORDNANCE,ENEMY,0,0,0,0,0,0,0,0,0
390737,MND-SE,2009-12-31 18:06,ENEMY ACTION,INDIRECT FIRE,ENEMY,0,0,0,0,0,0,1,0,0

In [11]:
df

,Region,Datetime,Type,Category,Affiliation,Detained,Enemy_KIA,Friend_KIA,Civilian_KIA,Host_nation_KIA,Enemy_WIA,Friend_WIA,Civilian_WIA,Host_nation_WIA,Complex_attack,Type_of_unit,MGRS
0,MNF-W,2004-01-01 06:06,Explosive Hazard,IED Explosion,ENEMY,0,0,0,0,0,0,0,0,0,False,None Selected,38SLC40
1,MNF-W,2004-01-01 14:02,Friendly Action,Confiscation,FRIEND,2,0,0,0,0,0,0,0,0,False,None Selected,38SLC40
2,MND-N,2004-01-01 07:07,Enemy Action,Indirect Fire,ENEMY,0,0,0,0,0,0,0,0,0,False,None Selected,38SME11
3,MND-N,2004-01-01 12:12,Criminal Event,Murder,ENEMY,0,0,0,1,0,0,0,0,0,False,None Selected,38SLF32
4,MNF-W,2004-01-01 12:12,Explosive Hazard,IED Found/Cleared,ENEMY,0,0,0,0,0,0,0,0,0,False,None Selected,38SLB98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390733,MND-N,2009-12-31 21:09,Explosive Hazard,IED Explosion,ENEMY,0,0,0,0,0,0,0,0,0,NaN,ISF,38SLE47
390734,MND-BAGHDAD,2009-12-31 22:10,Explosive Hazard,IED Found/Cleared,ENEMY,0,0,0,0,0,0,0,0,0,NaN,ISF,38SMB4983
390735,MND-SE,2009-12-31 22:10,Non-Combat Event,Accident,NEUTRAL,0,0,0,3,0,0,0,0,0,NaN,CF,38SMB52
390736,MND-BAGHDAD,2009-12-31 22:10,Explosive Hazard,Unexploded Ordnance,ENEMY,0,0,0,0,0,0,0,0,0,NaN,CF,38SMB3588
390737,MND-SE,2009-12-31 18:06,Enemy Action,Indirect Fire,ENEMY,0,0,0,0,0,0,1,0,0,NaN,CF,38SMB42

In [32]:
df.to_csv("iraq1.csv", index=False)

In [9]:
df = pd.read_csv('iraq.csv')

/var/folders/1w/6vqfb5jj0nv8pf9fqf_nwwfh0000gn/T/ipykernel_34157/1088039647.py:1: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('iraq.csv')

In [26]:

# Apply standardization to each column
for col in df.columns:
    if df[col].dtype == 'object' or df[col].dtype == 'string':  # Apply to object (string) or string columns
        df[col] = df[col].astype(str).str.upper().str.strip()

# Saving the dataframe

In [15]:
df = pd.read_csv('iraq1.csv')
df.dtypes

/var/folders/1w/6vqfb5jj0nv8pf9fqf_nwwfh0000gn/T/ipykernel_17428/4088273940.py:1: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('iraq1.csv')

Region             object
Datetime           object
Type               object
Category           object
Affiliation        object
Detained            int64
Enemy_KIA           int64
Friend_KIA          int64
Civilian_KIA        int64
Host_nation_KIA     int64
Enemy_WIA           int64
Friend_WIA          int64
Civilian_WIA        int64
Host_nation_WIA     int64
Complex_attack     object
Type_of_unit       object
MGRS               object
dtype: object

In [8]:
df["Affiliation"].unique()

array(['ENEMY', 'FRIEND', 'NEUTRAL', 'UNKNOWN'], dtype=object)

In [3]:
print(df.describe())

            Detained      Enemy_KIA     Friend_KIA   Civilian_KIA
count  390738.000000  390738.000000  390738.000000  390738.000000  \
mean        0.469161       0.060885       0.009628       0.168210
std         2.997439       0.973538       0.163002       1.609765
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         0.000000       0.000000       0.000000       0.000000
75%         0.000000       0.000000       0.000000       0.000000
max       560.000000     262.000000      31.000000     436.000000

       Host_nation_KIA      Enemy_WIA     Friend_WIA   Civilian_WIA
count    390738.000000  390738.000000  390738.000000  390738.000000  \
mean          0.038740       0.016512       0.080141       0.252694
std           0.382317       0.514484       0.642237       3.249681
min           0.000000       0.000000       0.000000       0.000000
25%           0.000000       0.000000       0.000000       0.000000
50%           0.000000       0.000000       0.000000       0.000000
75%           0.000000       0.000000       0.000000       0.000000
max          48.000000     194.000000     118.000000     641.000000

       Host_nation_WIA
count    390738.000000
mean          0.100016
std           0.812777
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max          97.000000

In [4]:
df.head()

,Region,Datetime,Type,Category,Affiliation,Detained,Enemy_KIA,Friend_KIA,Civilian_KIA,Host_nation_KIA,Enemy_WIA,Friend_WIA,Civilian_WIA,Host_nation_WIA,Complex_attack,Type_of_unit,MGRS
0,MNF-W,2004-01-01 06:06,Explosive Hazard,IED Explosion,ENEMY,0,0,0,0,0,0,0,0,0,False,None Selected,38SLC40
1,MNF-W,2004-01-01 14:02,Friendly Action,Confiscation,FRIEND,2,0,0,0,0,0,0,0,0,False,None Selected,38SLC40
2,MND-N,2004-01-01 07:07,Enemy Action,Indirect Fire,ENEMY,0,0,0,0,0,0,0,0,0,False,None Selected,38SME11
3,MND-N,2004-01-01 12:12,Criminal Event,Murder,ENEMY,0,0,0,1,0,0,0,0,0,False,None Selected,38SLF32
4,MNF-W,2004-01-01 12:12,Explosive Hazard,IED Found/Cleared,ENEMY,0,0,0,0,0,0,0,0,0,False,None Selected,38SLB98

In [5]:
df["Category"].unique()

array(['IED Explosion', 'Confiscation', 'Indirect Fire', 'Murder',
       'IED Found/Cleared', 'Raid', 'Cache Found/Cleared', 'Accident',
       'Direct Fire', 'Other', 'Cordon/Search', 'Detain', 'Tribal Feud',
       'Attack', 'Surveillance', 'Equipment Failure', 'Arson',
       'Unknown Explosion', 'Arrest', 'Unexploded Ordnance',
       'Other offensive', 'Blue-White', 'Theft', 'Demonstration',
       'IED Suspected', 'Mine Found/Cleared', 'Kidnapping',
       'Supporting CF', 'Mine Strike', 'Vehicle Interdiction', 'Looting',
       'Escalation of Force', 'arrest', 'Other Offensive',
       'Indirect Fire threat', 'Indirect Fire Threat', 'SAFIRE',
       'IED Hoax', 'Smuggling', 'accident', 'TCP', 'Patrol',
       'Attack Threat', 'Explosive Remnants of War (ERW)/Turn in',
       'IED False', 'Sabotage', 'Meeting', 'Medevac',
       'Direct Fire Threat', 'Blue-Blue', 'IED Threat', 'Carjacking',
       'Recon', 'Murder Threat', 'Indirect fire', 'Green-Green',
       'Police Actions', 'Assassination', 'Propaganda', 'murder',
       'Tests of Security', 'Counter Mortar Fire', 'Intimidation',
       'Direct fire', 'Repetitive Activities', 'detain', 'Blue-Green',
       'Small Unit Actions', 'Sniper Ops', 'confiscation', 'Border Ops',
       'Ambush', 'other', 'smuggling', 'SAFIRE Threat',
       'Close Air Support', 'Other Defensive', 'Green-White',
       'kidnapping', 'Ambush Threat', 'Green-Blue', 'Movement to Contact',
       'Attack threat', 'Breaching', 'Sniper ops', 'meeting',
       'Counter Mortar Patrol', 'Supporting AIF', 'Rock Throwing',
       'Sermon', 'other Defensive', 'Hijacking', 'Unknown explosion',
       'escalation of force', 'Theft Threat', 'ARTY', 'Detention',
       'IED suspected', 'Tests of security', 'raid', 'MEDEVAC', 'UAV',
       'Assassination Threat', 'Unexploded ordnance', 'Kidnapping Threat',
       'Intimidation Threat', 'Smuggling Threat', 'Sniper Ops Threat',
       'Carjacking Threat', 'Sabotage Threat', 'IED Found/cleared',
       'Convoy', 'Natural Disaster', 'White-Blue', 'Extortion', 'Mugging',
       'Small Arms Threat', 'Looting Threat', 'Elicitation',
       'Deliberate Attack', 'COnfiscation', 'Search and Attack',
       'Raid Threat', 'SUPPORTING CF', 'Staff Estimate', 'IED EXPLOSION',
       'IED FOUND/CLEARED', 'UNEXPLODED ORDNANCE', 'DETAIN', nan,
       'White-White', 'EQUIPMENT FAILURE', 'CACHE FOUND/CLEARED',
       'White-Green', 'Explosive Remnants of War (ERW)/Turn In',
       'GREEN-WHITE', 'ESCALATION OF FORCE', 'ARREST', 'CONFISCATION',
       'Explosive Remnants of War (ERW) Found/Cleared',
       'IED Pre-detonation', 'EXPLOSIVE REMNANTS OF WAR (ERW)/TURN IN',
       'Recon Threat', 'Lasing', 'MURDER', 'Shooting', 'CORDON/SEARCH',
       'OTHER', 'LASING', 'EXPLOSIVE REMNANTS OF WAR (ERW) FOUND/CLEARED',
       'None Selected'], dtype=object)

In [6]:
count = df['Category'].value_counts()

count

#wir sehen, dass S und NE als eigene Regionen keinen Sinn machen und inklduieren sie in SE und N

Category
IED Explosion          65229
Direct Fire            57660
IED Found/Cleared      44539
Indirect Fire          33594
Cache Found/Cleared    24760
                       ...
CONFISCATION               1
other Defensive            1
raid                       1
other                      1
Small Arms Threat          1
Name: count, Length: 150, dtype: int64

In [91]:
count = df["Region"].value_counts()
count

Region
MND-N             134266
MND-BAGHDAD       109803
MNF-W              75153
MND-C              45193
MND-SE             22516
MND-S               3460
                    1077
MND-NE               347
NONE SELECTED         17
Name: count, dtype: int64

In [92]:
# Replace 'MND-S' with 'MND-SE'
df["Region"] = df["Region"].replace('MND-S ', 'MND-SE ')
df["Region"] = df["Region"].replace('MND-NE ', 'MND-N ')

In [93]:
df['Region'].replace('NONE SELECTED ', np.nan, inplace=True)

In [94]:
df['Region'].replace(' ', np.nan, inplace=True)

In [95]:
df.dropna(subset=['Region'], inplace=True)

In [96]:
count = df["Region"].value_counts()
count

Region
MND-N           134613
MND-BAGHDAD     109803
MNF-W            75153
MND-C            45193
MND-SE           25976
Name: count, dtype: int64

In [111]:

# Write DataFrame to csv
df.to_csv('iraq.csv', index=False)

In [99]:
df.dtypes

Region             object
Datetime           object
Type               object
Category           object
Affiliation        object
Detained            int64
Enemy_KIA           int64
Friend_KIA          int64
Civilian_KIA        int64
Host_nation_KIA     int64
Enemy_WIA           int64
Friend_WIA          int64
Civilian_WIA        int64
Host_nation_WIA     int64
Complex_attack     object
Type_of_unit       object
MGRS               object
dtype: object

In [100]:
df["Region"] = df["Region"].str.strip()
df["Datetime"] = df["Datetime"].str.strip()
df["Type"] = df["Type"].str.strip()
df["Category"] = df["Category"].str.strip()
df["Affiliation"] = df["Affiliation"].str.strip()
df["Complex_attack"] = df["Complex_attack"].str.strip()

In [110]:
df["Host_nation_KIA"].value_counts()

Host_nation_KIA
0     381814
1       6367
2       1327
3        510
4        302
5        128
6        101
7         41
8         28
9         22
10        21
11        19
15        15
12        11
14         5
13         5
16         3
20         2
24         2
28         2
19         2
26         2
18         2
21         1
17         1
31         1
23         1
29         1
25         1
48         1
Name: count, dtype: int64

In [108]:
df.drop(columns=["MGRS"])

,Region,Datetime,Type,Category,Affiliation,Detained,Enemy_KIA,Friend_KIA,Civilian_KIA,Host_nation_KIA,Enemy_WIA,Friend_WIA,Civilian_WIA,Host_nation_WIA,Complex_attack,Type_of_unit
0,MNF-W,2004-01-01 06:06,Explosive Hazard,IED Explosion,ENEMY,0,0,0,0,0,0,0,0,0,FALSE,None Selected
1,MNF-W,2004-01-01 14:02,Friendly Action,Confiscation,FRIEND,2,0,0,0,0,0,0,0,0,FALSE,None Selected
2,MND-N,2004-01-01 07:07,Enemy Action,Indirect Fire,ENEMY,0,0,0,0,0,0,0,0,0,FALSE,None Selected
3,MND-N,2004-01-01 12:12,Criminal Event,Murder,ENEMY,0,0,0,1,0,0,0,0,0,FALSE,None Selected
4,MNF-W,2004-01-01 12:12,Explosive Hazard,IED Found/Cleared,ENEMY,0,0,0,0,0,0,0,0,0,FALSE,None Selected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391827,MND-N,2009-12-31 21:09,Explosive Hazard,IED Explosion,ENEMY,0,0,0,0,0,0,0,0,0,,ISF
391828,MND-BAGHDAD,2009-12-31 22:10,Explosive Hazard,IED Found/Cleared,ENEMY,0,0,0,0,0,0,0,0,0,,ISF
391829,MND-SE,2009-12-31 22:10,Non-Combat Event,Accident,NEUTRAL,0,0,0,3,0,0,0,0,0,,CF
391830,MND-BAGHDAD,2009-12-31 22:10,Explosive Hazard,Unexploded Ordnance,ENEMY,0,0,0,0,0,0,0,0,0,,CF
391831,MND-SE,2009-12-31 18:06,Enemy Action,Indirect Fire,ENEMY,0,0,0,0,0,0,1,0,0,,CF

In [41]:
df = df.set_index('Region')
bestdf = bestdf.set_index('Region')
df.update(bestdf)
df.reset_index(inplace=True)

ValueError: cannot reindex on an axis with duplicate labels

In [ ]:
import plotly.express as px
import pandas as pd
import json

# Load GeoJSON file
with open("iraq.json") as f:
    iraq_geojson = json.load(f)

In [ ]:
import pandas as pd
from pandas import json_normalize

# Assuming json_data is already loaded

# Convert JSON data to DataFrame
json_df = json_normalize(iraq_geojson['objects']['IRQ_adm1']['geometries'])

In [ ]:
json_df

In [ ]:


# Rename columns for a consistent mapping
json_df.rename(columns={'properties.NAME_1': 'Region', 'properties.ID_1': 'Region_ID'}, inplace=True)

In [ ]:
json_df

In [ ]:
import plotly.express as px
import pandas as pd
import json

# Load GeoJSON file
with open("iraq.json") as f:
    iraq_geojson = json.load(f)

# Function to extract coordinates from GeoJSON
def extract_coordinates(geojson):
    coordinates = []

    def extract_polygon_coords(polygon):
        for coord in polygon:
            coordinates.append(coord)
        return coordinates

    for feature in geojson['features']:
        geometry = feature['geometry']
        if geometry['type'] == 'Polygon':
            extract_polygon_coords(geometry['coordinates'][0])
        elif geometry['type'] == 'MultiPolygon':
            for polygon in geometry['coordinates']:
                extract_polygon_coords(polygon[0])
    return coordinates

# Extract coordinates
iraq_coordinates = extract_coordinates(iraq_geojson)
print(iraq_coordinates)

In [ ]:
import plotly.graph_objects as go
import geopandas as gpd
from shapely.geometry import Polygon